#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
RFM Customer Segmentation Report Generator
Generate comprehensive reports and marketing insights
"""

import pandas as pd
import numpy as np
from datetime import datetime
import os
import json

class RFMReportGenerator:
    """Generate comprehensive reports for RFM customer segmentation analysis"""

    def __init__(self):
        """Initialize the report generator"""
        self.analysis_date = datetime.now()

    def generate_executive_summary(self, rfm_df, summary_stats):
        """
        Generate executive summary report

        Args:
            rfm_df (pd.DataFrame): Complete RFM analysis results
            summary_stats (dict): Summary statistics by segment

        Returns:
            str: Executive summary report
        """
        total_customers = len(rfm_df)
        total_revenue = rfm_df['金额性'].sum()
        avg_customer_value = rfm_df['金额性'].mean()

        report = f"""
# RFM客户分群分析执行摘要
# RFM Customer Segmentation Executive Summary

**分析日期:** {self.analysis_date.strftime('%Y年%m月%d日 %H:%M')}

## 📊 核心发现 | Key Findings

### 客户概况 | Customer Overview
- **总客户数:** {total_customers:,} 人
- **总收入:** ￥{total_revenue:,.0f}
- **平均客户价值:** ￥{avg_customer_value:,.0f}
- **数据覆盖期间:** {rfm_df['最近性'].max()} 天购买历史

### 客户分群分布 | Segment Distribution
"""

        for segment, stats in summary_stats.items():
            segment_name = {'High': '高价值', 'Medium': '中等价值', 'Low': '低价值'}[segment]
            revenue_pct = stats['收入贡献占比'].replace('%', '')
            report += f"""
- **{segment_name}客户:** {stats['客户数量']} 人 ({stats['客户占比']})
  - 平均消费: ￥{stats['平均消费金额']:,.0f}
  - 收入贡献: {stats['收入贡献占比']}
  - 平均RFM得分: {stats['平均RFM总分']:.1f}/9
"""

        report += f"""

## 🎯 营销建议 | Marketing Recommendations

### 高价值客户 (High Value)
- **立即行动:** 纳入VIP营销计划
- **策略:** 个性化服务、专属优惠、优先客服
- **预期效果:** 提升客户忠诚度，增加复购率

### 中等价值客户 (Medium Value)
- **重点目标:** 客户激活和价值提升
- **策略:** 交叉销售、向上销售、会员激励
- **预期效果:** 向高价值客户转化

### 低价值客户 (Low Value)
- **优化策略:** 重新激活或成本控制
- **策略:** 低成本触达、批量营销、流失预警
- **预期效果:** 识别潜在价值，降低服务成本

## 📈 预期ROI | Expected ROI

基于历史数据分析，针对不同客户群体的营销活动预期ROI：
- **高价值客户:** 300-500% (推荐投入最多资源)
- **中等价值客户:** 150-300% (重点关注转化)
- **低价值客户:** 50-150% (控制成本，批量操作)

## 📋 下一步行动 | Next Steps

1. **立即:** 导出VIP客户清单，启动个性化营销
2. **本周:** 制定中等价值客户激活计划
3. **本月:** 评估低价值客户策略效果
4. **季度:** 重新评估客户分群，调整策略

---

*本报告由RFM客户分群分析系统自动生成*
*Report generated by RFM Customer Segmentation Analysis System*
"""

        return report

    def generate_detailed_analysis_report(self, rfm_df, original_data=None):
        """
        Generate detailed technical analysis report

        Args:
            rfm_df (pd.DataFrame): Complete RFM analysis results
            original_data (pd.DataFrame, optional): Original transaction data

        Returns:
            str: Detailed analysis report
        """
        report = f"""
# RFM客户分群详细分析报告
# Detailed RFM Customer Segmentation Analysis Report

**生成时间:** {self.analysis_date.strftime('%Y-%m-%d %H:%M:%S')}
**分析工具:** RFM Customer Segmentation Engine v1.0

## 1. 数据概览 | Data Overview

### 数据质量评估
- **分析客户数:** {len(rfm_df):,} 人
- **数据完整性:** {self._assess_data_quality(rfm_df)}
- **分析期间:** {rfm_df['最近性'].max()} 天

### RFM指标统计
"""

        # RFM statistics
        for metric, name in [('最近性', 'Recency'), ('频率性', 'Frequency'), ('金额性', 'Monetary')]:
            mean_val = rfm_df[metric].mean()
            median_val = rfm_df[metric].median()
            std_val = rfm_df[metric].std()
            min_val = rfm_df[metric].min()
            max_val = rfm_df[metric].max()

            report += f"""
#### {name} ({metric})
- 平均值: {mean_val:.2f}
- 中位数: {median_val:.2f}
- 标准差: {std_val:.2f}
- 范围: {min_val:.0f} - {max_val:.0f}
"""

        report += f"""

## 2. 分群分析 | Segment Analysis

### 分群特征对比
"""

        # Segment comparison
        segment_comparison = self._create_segment_comparison_table(rfm_df)
        report += segment_comparison

        report += f"""

### 客户价值评分分布
"""

        # Score distribution analysis
        score_analysis = self._analyze_score_distribution(rfm_df)
        report += score_analysis

        if original_data is not None:
            report += f"""

## 3. 原始数据分析 | Original Data Analysis

### 交易数据概览
- **总订单数:** {len(original_data):,}
- **平均订单金额:** ￥{original_data['数量'].mean() * original_data['单价'].mean():.2f}
- **客户分布:** {original_data['用户码'].nunique()} 个独立客户

### 产品类别分析
"""

            # Product category analysis if available
            if '产品说明' in original_data.columns:
                product_analysis = self._analyze_product_categories(original_data)
                report += product_analysis

        report += f"""

## 4. 算法说明 | Algorithm Details

### RFM分析方法
1. **Recency (R):** 客户最近一次购买时间距离今天的天数
2. **Frequency (F):** 客户在分析期内的购买次数
3. **Monetary (M):** 客户在分析期内的总消费金额

### 评分机制
- 采用1-3分制评分，基于33%和66%分位数划分
- Recency: 距离购买时间越近，得分越高
- Frequency & Monetary: 数值越高，得分越高

### 聚类算法
- 使用K-means算法进行客户分群
- 自动确定最优聚类数（肘部法则）
- 标准化处理确保各指标权重一致

## 5. 业务洞察 | Business Insights

### 客户价值金字塔
```
高价值客户 (Top 20-30%)    ← 核心利润来源
    ↑
中等价值客户 (Middle 30-40%) ← 潜力客户
    ↑
低价值客户 (Bottom 30-40%)  ← 长尾客户
```

### 关键发现
1. **帕累托法则验证:** 高价值客户贡献了主要收入
2. **客户分层明显:** 不同分群间存在显著差异
3. **营销机会:** 中等价值客户具有最大提升潜力

## 6. 技术建议 | Technical Recommendations

### 数据质量改进
- 建议建立数据清洗自动化流程
- 实施异常订单监控机制
- 定期进行数据一致性检查

### 分析优化
- 考虑引入更多维度（如产品类别、地域）
- 实施动态分群机制
- 建立客户价值预测模型

### 系统集成
- 与CRM系统对接，实现实时分群
- 建立自动化营销触发机制
- 实施分群效果监控

---

*报告结束 - RFM客户分群分析系统*
"""

        return report

    def generate_marketing_insights(self, rfm_df):
        """
        Generate marketing-focused insights and recommendations

        Args:
            rfm_df (pd.DataFrame): Complete RFM analysis results

        Returns:
            str: Marketing insights report
        """
        report = f"""
# RFM客户分群营销洞察报告
# RFM Customer Segmentation Marketing Insights

**报告日期:** {self.analysis_date.strftime('%Y年%m月%d日')}

## 🎯 营销策略矩阵 | Marketing Strategy Matrix

### 高价值客户 (High Value) - "忠诚保卫战"
**特征描述:** 购买频次高，消费金额大，最近活跃

**营销策略:**
- **VIP专属服务:** 专属客服经理、优先发货、专属客服热线
- **个性化推荐:** 基于购买历史的高端产品推荐
- **忠诚度计划:** 积分加倍、专属礼品、生日特权
- **预防流失:** 主动关怀、定期回访、流失预警

**预期效果:**
- 客户留存率提升 20-30%
- 平均客单价提升 15-25%
- 推荐转化率提升 40-50%

**实施建议:**
- 立即建立VIP客户档案
- 设计专属营销活动
- 设置客户流失监控

### 中等价值客户 (Medium Value) - "价值提升战"
**特征描述:** 有一定购买频次，但消费金额或活跃度有提升空间

**营销策略:**
- **交叉销售:** 推荐相关产品类别
- **向上销售:** 引导购买高端产品
- **会员激励:** 升级会员等级特权
- **定期互动:** 新品优先体验、会员活动

**预期效果:**
- 30-40%转化为高价值客户
- 平均购买频次提升 25-35%
- 客单价提升 20-30%

**实施建议:**
- 分析购买模式，识别交叉销售机会
- 设计渐进式会员升级体系
- 建立客户互动日历

### 低价值客户 (Low Value) - "激活抢救战"
**特征描述:** 购买频次低，消费金额小，可能存在流失风险

**营销策略:**
- **重新激活:** 特惠促销、回归奖励
- **教育引导:** 产品使用指导、价值认知教育
- **社区运营:** 用户社区参与、口碑激励
- **成本控制:** 批量营销、自动化触达

**预期效果:**
- 15-25%重新激活
- 5-10%转化为中等价值客户
- 降低营销成本 30-40%

**实施建议:**
- 建立客户生命周期预警机制
- 设计低成本的自动化营销流程
- 定期清理无效客户数据

## 📅 营销活动日历 | Marketing Calendar

### 本周重点
- [ ] VIP客户1对1沟通
- [ ] 中等价值客户促销活动设计
- [ ] 低价值客户激活邮件发送

### 本月目标
- [ ] 高价值客户满意度调研
- [ ] 中等价值客户升级计划启动
- [ ] 低价值客户成本效益分析

### 季度规划
- [ ] 客户分群效果评估
- [ ] 营销策略优化调整
- [ ] 新分群标准制定

## 💡 创新营销思路 | Innovative Marketing Ideas

### 1. 生命周期营销
- **新客户阶段:** 欢迎礼包、引导教育
- **成长阶段:** 技能提升、成功案例分享
- **成熟阶段:** 深度服务、价值共创
- **衰退阶段:** 挽留激励、告别礼遇

### 2. 场景化营销
- **节日场景:** 定制化节日营销
- **生活场景:** 基于用户生活场景推荐
- **工作场景:** 职业相关的产品服务
- **社交场景:** 社交分享激励

### 3. 数据驱动营销
- **实时个性化:** 基于实时行为的个性化推荐
- **预测性营销:** 基于预测模型的主动营销
- **A/B测试:** 持续优化营销效果
- **多渠道协同:** 整合线上线下营销触点

## 📊 KPI监控体系 | KPI Monitoring System

### 核心指标
- **客户留存率:** 各分群客户月度留存
- **客户价值提升:** 各分群平均消费金额变化
- **转化率:** 分群间转化率和转化时间
- **营销ROI:** 各分群营销活动投入产出比

### 监控频率
- **日报:** 关键活动效果监控
- **周报:** 分群变化趋势分析
- **月报:** 整体策略效果评估
- **季报:** 长期趋势和策略调整

---

*营销洞察报告 - 让数据驱动增长*
"""

        return report

    def export_vip_customer_list(self, rfm_df, top_n=100):
        """
        Export VIP customer list for marketing campaigns

        Args:
            rfm_df (pd.DataFrame): Complete RFM analysis results
            top_n (int): Number of top customers to export

        Returns:
            pd.DataFrame: VIP customer list
        """
        # Filter high value customers and sort by total score
        vip_customers = rfm_df[rfm_df['客户价值'] == 'High'].copy()

        if len(vip_customers) == 0:
            # If no High value customers, take top by monetary value
            vip_customers = rfm_df.nlargest(top_n, '金额性')
        else:
            # Sort high value customers by total score and monetary value
            vip_customers = vip_customers.sort_values(
                ['RFM总分', '金额性', '频率性'],
                ascending=[False, False, False]
            )

        # Take top N customers
        vip_customers = vip_customers.head(top_n).copy()

        # Add ranking
        vip_customers['排名'] = range(1, len(vip_customers) + 1)

        # Add marketing insights
        vip_customers['营销优先级'] = vip_customers['排名'].apply(
            lambda x: '最高优先级' if x <= 10 else '高优先级' if x <= 50 else '中优先级'
        )

        # Select relevant columns
        export_columns = [
            '用户码', '排名', '营销优先级',
            'R_评分', 'F_评分', 'M_评分', 'RFM总分',
            '最近性', '频率性', '金额性'
        ]

        vip_export = vip_customers[export_columns].copy()

        # Rename columns for clarity
        column_mapping = {
            '用户码': '客户ID',
            '排名': 'VIP排名',
            '营销优先级': '营销建议',
            'R_评分': '最近性评分',
            'F_评分': '频率性评分',
            'M_评分': '金额性评分',
            'RFM总分': '综合得分',
            '最近性': '最近购买天数',
            '频率性': '购买频次',
            '金额性': '总消费金额'
        }

        vip_export = vip_export.rename(columns=column_mapping)

        # Save to CSV
        vip_export.to_csv('vip_customers_marketing_list.csv', index=False, encoding='utf-8-sig')

        return vip_export

    def _assess_data_quality(self, df):
        """Assess data quality and completeness"""
        total_cells = len(df) * len(df.columns)
        missing_cells = df.isnull().sum().sum()
        completeness = ((total_cells - missing_cells) / total_cells) * 100

        if completeness >= 95:
            return "优秀 (Excellent)"
        elif completeness >= 90:
            return "良好 (Good)"
        elif completeness >= 80:
            return "一般 (Fair)"
        else:
            return "需要改进 (Needs Improvement)"

    def _create_segment_comparison_table(self, df):
        """Create detailed segment comparison table"""
        comparison = ""

        for segment in ['High', 'Medium', 'Low']:
            segment_data = df[df['客户价值'] == segment]
            segment_name = {'High': '高价值', 'Medium': '中等价值', 'Low': '低价值'}[segment]

            comparison += f"""
#### {segment_name}客户特征
- **客户数量:** {len(segment_data)} 人 ({len(segment_data)/len(df)*100:.1f}%)
- **平均最近购买:** {segment_data['最近性'].mean():.1f} 天前
- **平均购买频次:** {segment_data['频率性'].mean():.1f} 次
- **平均消费金额:** ￥{segment_data['金额性'].mean():,.0f}
- **平均RFM得分:** {segment_data['RFM总分'].mean():.1f}/9
"""

        return comparison

    def _analyze_score_distribution(self, df):
        """Analyze RFM score distribution"""
        analysis = """

### RFM评分分布分析
"""

        for score_type in ['R_评分', 'F_评分', 'M_评分']:
            score_dist = df[score_type].value_counts().sort_index()
            score_name = {
                'R_评分': '最近性评分',
                'F_评分': '频率性评分',
                'M_评分': '金额性评分'
            }[score_type]

            analysis += f"""
#### {score_name}分布
"""
            for score, count in score_dist.items():
                percentage = count / len(df) * 100
                analysis += f"- {score}分: {count} 人 ({percentage:.1f}%)\n"

        return analysis

    def _analyze_product_categories(self, df):
        """Analyze product categories if available"""
        if '产品说明' not in df.columns:
            return "产品类别数据不可用"

        analysis = """
#### 热销产品类别
"""

        # Top product categories
        product_revenue = df.groupby('产品说明')['订单金额'].sum().sort_values(ascending=False)
        top_products = product_revenue.head(10)

        for product, revenue in top_products.items():
            analysis += f"- {product}: ￥{revenue:,.0f}\n"

        return analysis

    def save_all_reports(self, rfm_df, original_data=None, output_dir='reports'):
        """
        Save all reports to files

        Args:
            rfm_df (pd.DataFrame): Complete RFM analysis results
            original_data (pd.DataFrame, optional): Original transaction data
            output_dir (str): Directory to save reports
        """
        os.makedirs(output_dir, exist_ok=True)

        # Generate summary statistics
        summary_stats = {}
        for segment in ['High', 'Medium', 'Low']:
            segment_data = rfm_df[rfm_df['客户价值'] == segment]
            if len(segment_data) > 0:
                summary_stats[segment] = {
                    '客户数量': len(segment_data),
                    '客户占比': f"{len(segment_data) / len(rfm_df) * 100:.1f}%",
                    '平均最近购买天数': segment_data['最近性'].mean(),
                    '平均购买频次': segment_data['频率性'].mean(),
                    '平均消费金额': segment_data['金额性'].mean(),
                    '总消费金额': segment_data['金额性'].sum(),
                    '收入贡献占比': f"{segment_data['金额性'].sum() / rfm_df['金额性'].sum() * 100:.1f}%",
                    '平均RFM总分': segment_data['RFM总分'].mean()
                }

        # Generate and save reports
        reports = {
            'executive_summary.md': self.generate_executive_summary(rfm_df, summary_stats),
            'detailed_analysis.md': self.generate_detailed_analysis_report(rfm_df, original_data),
            'marketing_insights.md': self.generate_marketing_insights(rfm_df)
        }

        for filename, content in reports.items():
            with open(os.path.join(output_dir, filename), 'w', encoding='utf-8') as f:
                f.write(content)

        # Export VIP customer list
        vip_list = self.export_vip_customer_list(rfm_df)

        print(f"所有报告已保存到: {output_dir}/")
        print(f"- executive_summary.md: 执行摘要")
        print(f"- detailed_analysis.md: 详细分析报告")
        print(f"- marketing_insights.md: 营销洞察报告")
        print(f"- vip_customers_marketing_list.csv: VIP客户清单")

def main():
    """Example usage"""
    generator = RFMReportGenerator()

    # Create sample data
    sample_data = pd.DataFrame({
        '用户码': range(100),
        '最近性': np.random.randint(1, 365, 100),
        '频率性': np.random.randint(1, 50, 100),
        '金额性': np.random.randint(100, 10000, 100),
        '客户价值': np.random.choice(['High', 'Medium', 'Low'], 100),
        'RFM总分': np.random.randint(3, 9, 100),
        'R_评分': np.random.randint(1, 4, 100),
        'F_评分': np.random.randint(1, 4, 100),
        'M_评分': np.random.randint(1, 4, 100)
    })

    # Generate sample reports
    generator.save_all_reports(sample_data)
    print("示例报告生成完成")

if __name__ == "__main__":
    main()